class Grocery{
	public static void main(String[] args){
	
	float danone_yogurt=60.0f;
	float yogurt=20.0f;
	float cottage_cheese=140.0f;
	float milk=22.0f;
	float cheese=1200f;
	float paneer_cheese=285.0f;
	float mozzarella_Cheese=262.0f;
	float butter=450.0f;
	float Watermelon=16.0f;
	float Onions = 20.0f;
	float Tomatoes=20.0f;
	float cucumbers=20.0f;
	float ginger_root=75.0f;
	float garlic = 185.0f;
	float carrots= 60.0f;
	float cabbage= 25.0f;
	float peppers= 70.0f;
	float dried_pineapples_chopped=800.0f;
	float dried_cranberry=1000.0f;
	float dried_strawberries= 1000.0f;
	float dried_red_cherry= 950.0f;
	float dried_prunes= 700.0f;
	float dried_golden_raisins= 240.0f;
	float the_Afghan_raisins= 500.0f;
	float dried_papaya= 600.0f;
	float dried_apricots= 680.0f;
	float turmeric= 165.0f;
	float not_powdered_turmeric=35.0f;
	float masala= 219.0f;
	float chile_masala= 285.0f;
	float kashmiri_chili_powder= 175.0f;
	float coriander= 175.0f;
	float black_pepper=100.0f;
	float dried_chile= 182.0f;
	float dried_Anise= 2000.0f;
	float sandwiches = 30.0f;
	float white_bread= 70.0f;
	float fresh_tortillas = 22.0f;
	float hindu_goodies =30.0f;
	float gulab_jamuna= 14.0f;
	float rasgulla = 15.0f;
	float sweets=30.0f;
	float jams = 10.0f;
	float nutella=250.0f;
	float pasta= 60.0f;
	float lentils = 130.0f;
	float rice =150.0f;
	float[] items={danone_yogurt,yogurt,cottage_cheese, milk, cheese, paneer_cheese, mozzarella_Cheese, butter, Watermelon,Onions, Tomatoes, cucumbers, ginger_root, garlic, carrots, cabbage, peppers,dried_pineapples_chopped,dried_cranberry,dried_strawberries,dried_red_cherry,dried_prunes,dried_golden_raisins,the_Afghan_raisins,dried_papaya, dried_apricots,turmeric,not_powdered_turmeric,masala,chile_masala,kashmiri_chili_powder,coriander,black_pepper,dried_chile, dried_Anise,sandwiches, white_bread,fresh_tortillas, hindu_goodies, gulab_jamuna, rasgulla, sweets, jams, nutella, pasta, lentils, rice};
	System.out.println("1.Price of danone_yogurt: "+items[0]);
	System.out.println("2.Price of yogurt: "+items[1]);
	System.out.println("3.Price of cottage_cheese: "+items[2]);
	System.out.println("4.Price of milk: "+items[3]);
	System.out.println("5.Price of cheese: "+items[4]);
	System.out.println("6.Price of paneer_cheese: "+items[5]);
	System.out.println("7.Price of mozzarella_Cheese: "+items[6]);
	System.out.println("8.Price of butter: "+items[7]);
	System.out.println("9.Price of Watermelon: "+items[8]);
	System.out.println("10.Price of Onions: "+items[9]);
	System.out.println("11.Price of Tomatoes: "+items[10]);
	System.out.println("12.Price of cucumbers: "+items[11]);
	System.out.println("13.Price of ginger_root: "+items[12]);
	System.out.println("14.Price of garlic: "+items[13]);
	System.out.println("15.Price of carrots: "+items[14]);
	System.out.println("16.Price of cabbage: "+items[15]);
	System.out.println("17.Price of peppers: "+items[16]);
	System.out.println("18.Price of dried_pineapples_chopped: "+items[17]);
	System.out.println("19.Price of dried_cranberry: "+items[18]);
	System.out.println("20.Price of dried_strawberries: "+items[19]);
	System.out.println("21.Price of dried_red_cherry: "+items[20]);
	System.out.println("22.Price of dried_prunes: "+items[21]);
	System.out.println("23.Price of dried_golden_raisins: "+items[22]);
	System.out.println("24.Price of the_Afghan_raisins: "+items[23]);
	System.out.println("25.Price of dried_papaya: "+items[24]);
	System.out.println("26.Price of dried_apricots: "+items[25]);
	System.out.println("27.Price of turmeric: "+items[26]);
	System.out.println("28.Price of not_powdered_turmeric: "+items[27]);
	System.out.println("29.Price of masala: "+items[28]);
	System.out.println("30.Price of chile_masala: "+items[29]);
	System.out.println("31.Price of kashmiri_chili_powder: "+items[30]);
	System.out.println("32.Price of coriander: "+items[31]);
	System.out.println("33.Price of black_pepper: "+items[32]);
	System.out.println("34.Price of dried_chile: "+items[33]);
	System.out.println("35.Price of dried_Anise: "+items[34]);
	System.out.println("36.Price of sandwiches: "+items[35]);
	System.out.println("37.Price of white_bread: "+items[36]);
	System.out.println("38.Price of fresh_tortillas: "+items[37]);
	System.out.println("39.Price of  hindu_goodies: "+items[38]);
	System.out.println("40.Price of  gulab_jamuna: "+items[39]);
	System.out.println("41.Price of rasgulla: "+items[40]);
	System.out.println("42.Price of sweets: "+items[41]);
	System.out.println("43.Price of  jams: "+items[42]);
	System.out.println("44.Price of nutella: "+items[43]);
	System.out.println("45.Price of pasta: "+items[44]);
	System.out.println("46.Price of lentils: "+items[45]);
	System.out.println("47.Price of rice: "+items[46]);
	
	}
}
